# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "backend_app"

rule_files:

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]
    
  - job_name: "backend_app"
    dns_sd_configs:
      - names: ["backend_app"]
        port: 80
        type: A
        refresh_interval: 5s